"""init db

Revision ID: 7360d79a5c89
Revises: 
Create Date: 2025-05-10 11:01:42.478745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7360d79a5c89'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events_contact_description',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=False),
    sa.Column('event_id', sa.VARCHAR(), nullable=False),
    sa.Column('updated_by', sa.VARCHAR(), nullable=False),
    sa.Column('updated_at', sa.VARCHAR(), nullable=False),
    sa.Column('updated_date', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('neivethiyam_names',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('amount', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('start_at', sa.VARCHAR(), nullable=False),
    sa.Column('end_at', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events_status',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=9), nullable=True),
    sa.Column('event_id', sa.VARCHAR(), nullable=False),
    sa.Column('added_by', sa.VARCHAR(), nullable=False),
    sa.Column('updated_by', sa.VARCHAR(), nullable=True),
    sa.Column('image_url', sa.VARCHAR(), nullable=True),
    sa.Column('feedback', sa.VARCHAR(), nullable=True),
    sa.Column('archagar', sa.VARCHAR(), nullable=True),
    sa.Column('abisegam', sa.VARCHAR(), nullable=True),
    sa.Column('helper', sa.VARCHAR(), nullable=True),
    sa.Column('poo', sa.VARCHAR(), nullable=True),
    sa.Column('read', sa.VARCHAR(), nullable=True),
    sa.Column('prepare', sa.VARCHAR(), nullable=True),
    sa.Column('updated_date', sa.DATE(), nullable=True),
    sa.Column('updated_at', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_table('events_neivethiyam',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('neivethiyam_id', sa.INTEGER(), nullable=False),
    sa.Column('event_id', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['neivethiyam_id'], ['neivethiyam_names.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clients',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('mobile_number', sa.VARCHAR(), nullable=False),
    sa.Column('city', sa.VARCHAR(), nullable=False),
    sa.Column('event_id', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('mobile_number', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('role', sa.VARCHAR(length=5), nullable=False),
    sa.Column('password', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('total_amount', sa.INTEGER(), nullable=False),
    sa.Column('paid_amount', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=14), nullable=False),
    sa.Column('mode', sa.VARCHAR(length=28), nullable=True),
    sa.Column('event_id', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_status_images',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('image', sa.BLOB(), nullable=True),
    sa.Column('event_sts_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['event_sts_id'], ['events_status.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_names',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('amount', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_names')
    op.drop_table('event_status_images')
    op.drop_table('payments')
    op.drop_table('users')
    op.drop_table('clients')
    op.drop_table('events_neivethiyam')
    op.drop_table('events_status')
    op.drop_table('events')
    op.drop_table('neivethiyam_names')
    op.drop_table('events_contact_description')
    
    # ### end Alembic commands ###
